<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>

    <body>
        <div>
            <div class="adver"></div>
        </div>
        <script>
            // const p = new Promise((resolve, reject) => {
            //     throw 3
            // })
            // p.then(
            //     value => { },
            //     reason => { console.log('reason1' + reason); }
            // )
            // p.then(
            //     value => { },
            //     reason => { console.log('reason2' + reason); }
            // )
            // 常规：先指定回调，再改变状态
            // new Promise((resolve, reject) => {
            //     setTimeout(() => {
            //         resolve(1) // 2.后改变的状态（同时指定数据），异步执行回调函数
            //     }, 1000);
            // }).then( //1.先指定的函数，保存当前指定的回调函数
            //     value => { },
            //     reason => { console.log('reason', reason); })
            // 先改状态，再指定回调
            // 方法一
            // new Promise((resolve, reject) => {
            //     resolve(1) // 1.先改变的状态（同时指定数据），异步执行回调函数
            // }).then( //2.后指定的函数，保存当前指定的回调函数
            //     value => { console.log('value2', value); },
            //     reason => { console.log('reason2', reason); })
            // console.log('-------');
            // 方法二
            // const p = new Promise((resolve, reject) => {
            //     setTimeout(() => {
            //         resolve(1) // 1.先改变的状态（同时指定数据），异步执行回调函数
            //     }, 1000);
            // })
            // setTimeout(() => {
            //     p.then( //2.后指定的函数，保存当前指定的回调函数
            //         value => { console.log('value3', value); },
            //         reason => { console.log('reason3', reason); })
            // }, 1100);//设置的定时器比上面的异步回调时间长即可

            // new Promise((resolve, reject) => {
            //     // resolve(1)
            //     reject(1)
            // }).then(
            //     value => {
            //         console.log('onResolved1--' + value);
            //         // return 2 // 直接 return 一个值
            //         // return Promise.resolve(2)//成功状态值为2的Promise对象
            //         // return Promise.reject(2)//失败状态值为3的Promise对象
            //         // throw 5
            //     },
            //     reason => {
            //         console.log('onRejcected1--' + reason);
            //         // return Promise.resolve(2)//成功状态值为2的Promise对象
            //         // return Promise.reject(3)//失败状态值为3的Promise对象
            //         // throw 5

            //     }
            // ).then(
            //     value => {
            //         console.log('onResolved2--' + value);
            //     },
            //     reason => {
            //         console.log('onRejcected2--' + reason);
            //     }
            // )

            // new Promise((resolve, reject) => {
            //     setTimeout(() => {
            //         console.log('执行任务1-异步');
            //         resolve(1)
            //     }, 1000);
            // }).then(
            //     value => {
            //         console.log('任务1的结果', value);
            //         console.log('执行任务2--同步');
            //         return 2
            //     }
            // ).then(
            //     value => {
            //         console.log('任务2的结果', value);
            //         return new Promise((resolve, reject) => {
            //             setTimeout(() => {
            //                 console.log('执行任务3--异步');
            //                 resolve(3);
            //             }, 1000);
            //         })
            //     }
            // ).then(value => {
            //     console.log('任务3的结果', value);
            // })

            // new Promise((resolve, reject) => {
            //     resolve(1)
            //     reject(2)
            // }).then(
            //     value => {
            //         console.log('onResolved-成功', value);
            //         // return Promise.resolve(3)
            //         // return Promise.reject(3)
            //         throw 3
            //     },
            //     reason => {
            //         console.log('onRejected-失败', reason);
            //         // return Promise.resolve(3)
            //         // return Promise.reject(3)
            //         // throw 3
            //     }
            // ).then(
            //     value => {
            //         console.log('onResolved-成功', value);
            //     },
            //     reason => {
            //         console.log('onRejected-失败', reason);
            //     }
            // )

            new Promise((resolve, reject) => {
                // resolve(1)
                reject(2);
            })
                .then(
                    (value) => {
                        console.log("onResolved", value);
                    },
                    (reason) => {
                        throw reason;
                    }
                )
                .then(
                    (value) => {
                        console.log("onResolved", value);
                    },
                    (reason) => {
                        throw reason;
                    }
                )
                .then(
                    (value) => {
                        console.log("onResolved", value);
                    },

                    (reason) => Promise.reject(reason)
                )
                .catch((reason) => {
                    console.log("onRejected", reason);
                    // throw reason
                    // return Promise.reject(reason);
                    // 没有throw reason 或者 return Promise.reject(reason) 下一个.then()的值是 resolve ：undefined ，因为返回值是 undefined
                    //
                    // 中断执行链式调用
                    //返回一个新的状态为pending的promise对象即可
                    return new Promise(() => {});
                })
                .then(
                    (value) => {
                        console.log("onResolved2", value);
                    },
                    (reason) => {
                        console.log("onRejected2", reason);
                    }
                );

            const PENDING = "pending";
            const FULFILLED = "fulfilled";
            const REJECTED = "rejected";
            function MyPromise(fn) {
                let _this = this;
                _this.value = undefined;
                _this.reason = undefined;
                _this.status = PENDING;
                function resolve(value) {
                    if (_this.status === PENDING) {
                        _this.status = FULFILLED;
                        _this.value = value;
                    }
                }
                function reject(reason) {
                    if (_this.status === PENDING) {
                        _this.status = REJECTED;
                        _this.reason = reason;
                    }
                }
                try {
                    fn(resolve, reject);
                } catch (error) {
                    reject(error);
                }
            }
            MyPromise.prototype.then = function(onFulfilled, onRejected) {
                let _this = this;
                switch (_this.status) {
                    case "fulfilled":
                        onFulfilled(_this.value);
                        break;
                    case "rejected":
                        onRejected(_this.reason);
                        break;
                    default:
                }
            };
            var p = new MyPromise(function(resolve, reject) {
                resolve(1);
            });
            p.then(function(x) {
                console.log(x);
            });
        </script>
    </body>
</html>
